### ISSUE TITLE
New changes

### ISSUE THREAD

**Issue by virajvchavan** [Neelam618/Brain-in-Pocket-Website#2]
- Change address to Pune, MH
- Change text under Our Social Networks
- Remove redundant titles
- Hide featured services (don't remove the code)
- Make the logo smaller for mobile screens
- make the hero image size as small as possible

**Comment by virajvchavan** [comment]
@Neelam618 Make these changes in a new branch and create a Pull Request.

**Comment by Neelam618** [comment]
https://github.com/Neelam618/Brain-in-Pocket-Website/pull/3

**Comment by Neelam618** [comment]
done
